name = "GraphSignals"
uuid = "3ebe565e-a4b5-49c6-aed2-300248c3a9c1"
authors = ["Yueh-Hua Tu"]
version = "0.1.0"

[deps]
GraphLaplacians = "a1251efa-393a-423f-9d7b-faaecba535dc"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1.4, 1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
