name = "GraphSignals"
uuid = "3ebe565e-a4b5-49c6-aed2-300248c3a9c1"
authors = ["Yueh-Hua Tu <a504082002@gmail.com>"]
version = "0.2.3"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
GraphLaplacians = "a1251efa-393a-423f-9d7b-faaecba535dc"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CUDA = "2.5 - 3.3"
ChainRulesCore = "0.10, 1"
FillArrays = "0.11 - 0.12"
Functors = "0.2"
GraphLaplacians = "0.1"
LightGraphs = "1.3"
NNlib = "0.7"
julia = "1.6"

[extras]
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["ChainRulesTestUtils", "FiniteDifferences", "SimpleWeightedGraphs", "Test", "Zygote"]
