name = "GraphSignals"
uuid = "3ebe565e-a4b5-49c6-aed2-300248c3a9c1"
authors = ["Yueh-Hua Tu <a504082002@gmail.com>"]
version = "0.1.1"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GraphLaplacians = "a1251efa-393a-423f-9d7b-faaecba535dc"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
FillArrays = "0.9"
GraphLaplacians = "0.1"
LightGraphs = "1.3"
SimpleWeightedGraphs = "1.1"
Zygote = "0.4 - 0.5"
julia = "1.4 - 1.5"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CUDA"]
